### PR TITLE
#1 added posibility to change the CsQuery factory

### PR DESCRIPTION
**Pull request by wobu**
now you can provide a custom CQ instance via:

		private static readonly HtmlSanitizer DefaultSanitizer = 
			new HtmlSanitizer(
				csQueryFactory: html => CQ.Create(html, docType: DocType.XHTML));

Note: i haven't provide any test case, dunno if it is necessary for this.

Please give feedback if this feature could make it to a, hopefully soon, release.
Cause i need it and currently i replaced the local resolved nuget packages with my own compiled one...

### CODE REVIEW

**Comment by 304NotModified** [comment]
Looks good but I'm not sure if this should be a constructor parameter.

**Comment by wobu** [comment]
wanted to add this as method parameter of Sanitize() but this wasn't possible in C# with Func.

**Comment by 304NotModified** [comment]
A method parameter is possible? Anyway, I was more thinking of a public property (instead of parameter) .

**Comment by 304NotModified** [comment]
How does this fix #1? Is this with the beta of csquery?

**Comment by wobu** [comment]
Anyway, do as u want. I am not so familiar with C# anymore ...

i noticed with my example above.

     will be to 

but 

   <br /> will sill be converted to <br>

but that was the only exception i found.

**Comment by mganss** [comment]
Doing `CQ.Create(html, docType: DocType.XHTML)` didn't work for me at all :crying_cat_face: But it turns out there's an easier way. Do
```C#
CsQuery.Config.DocType = DocType.XHTML;
```
before calling `Sanitize()` and all is well.

**Comment by wobu** [comment]
hmpf, this Solution is mutable and will affect all usages within one Application.

What's with several usages with different configurations?

**Comment by 304NotModified** [comment]
I agree, a non-global setting has the preference.

**Comment by mganss** [comment]
I'd prefer a per-instance solution as well, although I'd expect the need for different configurations within a single application to be pretty rare. This doesn't work:
```C#
var html = @"<div><img src=""xyz""><br></div>";
var cq = CQ.Create(html, docType: DocType.XHTML);
var output = cq.Render(); // same as original
```
Neither does this:
```C#
var html = @"<div><img src=""xyz""><br></div>";
var cq = CQ.Create(html, docType: DocType.XHTML);
cq.Document.DocTypeNode = new DomDocumentType(DocType.XHTML);
var output = cq.Render(); // <!DOCTYPE html PUBLIC><div><img src="xyz" /><br /></div>
```

Other ideas?

**Pull request closed without merging**
