### PR TITLE
	fix to overcome the 1024 uri limit from System.Uri for base64 images

### PR DESCRIPTION
**Pull request by BogdanDamianC**
the fix covers only uri used inside image src properties and only if the length is between 1k and 4M (the max size seems to be different depending on the browser)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Not sure if this should be in the core of the library 

Note: optional parameters aren't binary backwards-compatible.  This is a breaking change now.

**Comment by BogdanDamianC** [comment]
for the core part, do you mean the base64 check should be external to the library or it should not be part of the HtmlSanitizer class?

**Comment by 304NotModified** [comment]
The latter. But maybe there is a good reason?

**Comment by BogdanDamianC** [comment]
on one side the .net implementation does not cover this yet so it is a gap
on the other hand this is more of a patch for the .net implementation I guess I can keep it local

**Comment by BogdanDamianC** [comment]
are you ok with making the SanitizeUrl virtual ?

**Comment by 304NotModified** [comment]
> are you ok with making the SanitizeUrl virtual ?

Is this still needed? (as you closed the issue)

**Comment by BogdanDamianC** [comment]
no, I'm good.

On Mon, Jan 25, 2016 at 11:57 AM, Julian Verdurmen <notifications@github.com

**Pull request closed without merging**
